name: test

on:
  workflow_dispatch:

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Show generated tags (debug)
        run: |
          echo "OWNER = ${{ env.OWNER }}"
          echo "actor = ${{ github.actor }}"
          echo "meta tags = ${{ steps.meta-backend.outputs.tags }}"
      - name: show caddy
        run: |
          echo "tags = ${{ steps.meta-caddy.outputs.labels }}"

        